var data = [
	{
		"timestamp": "2/17/2015 10:39:34",
		"businessArea": "Finance/banking/insurance",
		"international": "No",
		"startup": "No",
		"employees": 2000,
		"tool": "Atlassian Jira",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "ISO 10006",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 12:08:48",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 10000,
		"tool": "Workspace",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "ISO 20000",
		"softwareManagementTools": "No",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 17:44:31",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 128000,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "No",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "All",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 17:51:05",
		"businessArea": "Administrative services",
		"international": "No",
		"startup": "No",
		"employees": 1000,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "",
		"toolType": "",
		"collaborative": "",
		"issueTracking": "",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "",
		"document": "",
		"reportingAnalysis": "",
		"timeTracking": null,
		"invoicing": "",
		"processes": "Don't know",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "in-house services",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 18:26:53",
		"businessArea": "Finance/banking/insurance",
		"international": "No",
		"startup": "No",
		"employees": 4,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "",
		"toolType": "",
		"collaborative": "",
		"issueTracking": "",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "",
		"document": "",
		"reportingAnalysis": "",
		"timeTracking": null,
		"invoicing": "",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 18:30:01",
		"businessArea": "Telecommunication/IT",
		"international": "No",
		"startup": "Yes",
		"employees": 4,
		"tool": "Basecamp",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "ISO 10006",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 19:18:40",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "No",
		"employees": 68000,
		"tool": "Microsoft Project",
		"anotherTool": "Atlassian Jira",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "Don't know",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 19:20:17",
		"businessArea": "Food",
		"international": "Yes",
		"startup": "Yes",
		"employees": 4,
		"tool": "Trello",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 20:05:30",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 120,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "No",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "ISO / IEC / IEEE 42010: 2011",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 20:28:56",
		"businessArea": "Telecommunication/IT",
		"international": "No",
		"startup": "No",
		"employees": 1,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "non",
		"toolType": "non",
		"collaborative": "",
		"issueTracking": "",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "",
		"document": "",
		"reportingAnalysis": "",
		"timeTracking": null,
		"invoicing": "",
		"processes": "No",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 21:28:14",
		"businessArea": "Research/hardware",
		"international": "Yes",
		"startup": "Yes",
		"employees": 6,
		"tool": "Git-Hub",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 21:40:57",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "Yes",
		"employees": 25,
		"tool": "Atlassian Jira",
		"anotherTool": "Trello",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/20/2015 22:27:06",
		"businessArea": "Finance/banking/insurance",
		"international": "No",
		"startup": "No",
		"employees": 1000,
		"tool": "Atlassian Jira",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 2,
		"pmQuality": 4
	},
	{
		"timestamp": "2/20/2015 22:45:43",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "No",
		"employees": 85,
		"tool": "Microsoft Project",
		"anotherTool": "Microsof Excel",
		"license": "Licensed",
		"webBased": "No",
		"toolType": "Workstation",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "CSAE 3416; ISAE 3402",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 4,
		"difficulty": 4,
		"pmQuality": 4
	},
	{
		"timestamp": "2/21/2015 7:43:46",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 1090,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "ISO 14001, ISO 27001, ISO 9001",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 3,
		"difficulty": 2,
		"pmQuality": 4
	},
	{
		"timestamp": "2/21/2015 9:35:39",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 1000,
		"tool": "Microsoft Project",
		"anotherTool": "Clarity",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "Don't know",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 4,
		"difficulty": 5,
		"pmQuality": 3
	},
	{
		"timestamp": "2/21/2015 11:30:46",
		"businessArea": "Web development",
		"international": "Yes",
		"startup": "No",
		"employees": 9,
		"tool": "teamwork",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Don't know",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 3,
		"difficulty": 4,
		"pmQuality": 3
	},
	{
		"timestamp": "2/21/2015 11:47:00",
		"businessArea": "Finance/banking/insurance",
		"international": "No",
		"startup": "No",
		"employees": 2900,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "No",
		"toolType": "Installed on server",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "No",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "2/21/2015 16:42:54",
		"businessArea": "Finance/banking/insurance",
		"international": "Yes",
		"startup": "No",
		"employees": 3000,
		"tool": "Atlassian Jira",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "Don't know",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 4,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "2/21/2015 23:18:08",
		"businessArea": "Telecommunication/IT",
		"international": "No",
		"startup": "No",
		"employees": 15,
		"tool": "None",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "ISO 20000",
		"softwareManagementTools": "No",
		"smHow": "I don§t manage project",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 3,
		"difficulty": 4,
		"pmQuality": 3
	},
	{
		"timestamp": "2/21/2015 23:30:18",
		"businessArea": "Software house/software consulting",
		"international": "No",
		"startup": "Yes",
		"employees": 1,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "Not applicable",
		"toolType": "Not applicable",
		"collaborative": "No",
		"issueTracking": "No",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "Small teams do not need to manage them",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 4,
		"pmQuality": 4
	},
	{
		"timestamp": "2/22/2015 19:26:52",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 100000,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "ISO 20000",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "2/23/2015 10:00:49",
		"businessArea": "Software house/software consulting",
		"international": "No",
		"startup": "No",
		"employees": 75,
		"tool": "Atlassian Jira",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 4,
		"difficulty": 5,
		"pmQuality": 5
	},
	{
		"timestamp": "2/23/2015 10:05:29",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "No",
		"employees": 500,
		"tool": "None",
		"anotherTool": "",
		"license": "Free",
		"webBased": "No",
		"toolType": "Installed on server",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "No",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 1,
		"satisfaction": 3,
		"difficulty": 2,
		"pmQuality": 1
	},
	{
		"timestamp": "2/25/2015 8:55:22",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "No",
		"employees": 30000,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "",
		"toolType": "",
		"collaborative": "",
		"issueTracking": "",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "",
		"document": "",
		"reportingAnalysis": "",
		"timeTracking": null,
		"invoicing": "",
		"processes": "No",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "270001, 9001, 140001",
		"softwareManagementTools": "No",
		"smHow": "I work in a small development team (even though in a big company) of just 2 people, no need for special software management among us.",
		"blank": null,
		"importanceOfSm": 0,
		"satisfaction": 0,
		"difficulty": 0,
		"pmQuality": 0
	},
	{
		"timestamp": "2/27/2015 0:18:09",
		"businessArea": "Finance/banking/insurance",
		"international": "No",
		"startup": "No",
		"employees": 866,
		"tool": "Atlassian Jira",
		"anotherTool": "Excel",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Don't know",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "20022",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 2,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "04/03/15 06:12 PM",
		"businessArea": "Education/research",
		"international": "Yes",
		"startup": "No",
		"employees": 10000,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "No",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Don't know",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 2,
		"difficulty": 2,
		"pmQuality": 2
	},
	{
		"timestamp": "04/03/15 06:22 PM",
		"businessArea": "Software house/software consulting",
		"international": "No",
		"startup": "No",
		"employees": 140,
		"tool": "Atlassian Jira",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "ISO9001,ISO27001",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 5,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "3/22/2015 14:06:39",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "Yes",
		"employees": 10,
		"tool": "Redmine",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "3/22/2015 14:16:04",
		"businessArea": "Telecommunication/IT",
		"international": "Yes",
		"startup": "Yes",
		"employees": 3,
		"tool": "Asana",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Don't know",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 4,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "3/22/2015 14:39:34",
		"businessArea": "Tourism/transport",
		"international": "Yes",
		"startup": "Yes",
		"employees": 4,
		"tool": "Trello",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 5,
		"difficulty": 5,
		"pmQuality": 5
	},
	{
		"timestamp": "3/22/2015 14:51:59",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "Yes",
		"employees": 30,
		"tool": "Trello",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "No",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "GitHub",
		"blank": null,
		"importanceOfSm": 2,
		"satisfaction": 4,
		"difficulty": 1,
		"pmQuality": 3
	},
	{
		"timestamp": "3/22/2015 17:11:41",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "Yes",
		"employees": 8,
		"tool": "Microsoft Project",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 4,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "3/22/2015 18:55:15",
		"businessArea": "Finance/banking/insurance",
		"international": "Yes",
		"startup": "No",
		"employees": 600,
		"tool": "Microsoft Project",
		"anotherTool": "Jira",
		"license": "Licensed",
		"webBased": "No",
		"toolType": "Installed on server",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 2,
		"pmQuality": 4
	},
	{
		"timestamp": "3/22/2015 21:29:13",
		"businessArea": "Telecommunication/IT",
		"international": "No",
		"startup": "Yes",
		"employees": 12,
		"tool": "Atlassian Jira",
		"anotherTool": "Basecamp",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 4,
		"difficulty": 4,
		"pmQuality": 4
	},
	{
		"timestamp": "3/22/2015 23:11:25",
		"businessArea": "Telecommunication/IT",
		"international": "No",
		"startup": "Yes",
		"employees": 10,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "",
		"toolType": "",
		"collaborative": "No",
		"issueTracking": "No",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "we use email for communication",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 4,
		"difficulty": 0,
		"pmQuality": 4
	},
	{
		"timestamp": "3/23/2015 8:58:40",
		"businessArea": "Software house/software consulting",
		"international": "No",
		"startup": "Yes",
		"employees": 0,
		"tool": "Getquantify",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "Getquantify is project management software!",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 5,
		"difficulty": 5,
		"pmQuality": 5
	},
	{
		"timestamp": "3/23/2015 9:18:00",
		"businessArea": "Software house/software consulting",
		"international": "No",
		"startup": "No",
		"employees": 4,
		"tool": "Own",
		"anotherTool": "",
		"license": "Own",
		"webBased": "part of it",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "No",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "Yes",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "3/23/2015 9:52:18",
		"businessArea": "Human resourses",
		"international": "Yes",
		"startup": "Yes",
		"employees": 5,
		"tool": "Trello",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Don't know",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 4,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "3/23/2015 10:08:04",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "Yes",
		"employees": 20,
		"tool": "TargetProcess",
		"anotherTool": "Trello",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 4,
		"difficulty": 4,
		"pmQuality": 4
	},
	{
		"timestamp": "3/23/2015 14:50:34",
		"businessArea": "Software house/software consulting",
		"international": "Yes",
		"startup": "Yes",
		"employees": 50,
		"tool": "Atlassian Jira",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Installed on server",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes", /*, partially. It is not a pure PM methodology, as the firm is relatively new. The processes are slowly being introduced into practice within the firm.*/
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "Even though the company does not directly use PM software (like e.g. Microsoft Project), the company still maintains its project plans and other knowledge base using other, usually, widely-spread tools, like, for instance, Confluence, Jira, etc.\nThe company uses Kanban methodology for software development. This methodology has its roots in manufacturing, especially in Kaizen (set of rules to increase quality originated in Japan) and in Theory of Constraints (a tool to increase throughput in processing) developed by Elli Goldrath.",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 4,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "3/23/2015 15:07:23",
		"businessArea": "SaaS",
		"international": "Yes",
		"startup": "Yes",
		"employees": 15,
		"tool": "Asana",
		"anotherTool": "Harvest, Bitbucket, Slack,",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "No",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 5,
		"difficulty": 5,
		"pmQuality": 5
	},
	{
		"timestamp": "3/24/2015 15:13:59",
		"businessArea": "Human resourses",
		"international": "Yes",
		"startup": "Yes",
		"employees": 5,
		"tool": "None",
		"anotherTool": "No",
		"license": "None",
		"webBased": "N/A",
		"toolType": "N/A",
		"collaborative": "No",
		"issueTracking": "Yes",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "Yes",
		"document": "Yes",
		"reportingAnalysis": "Yes",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Yes",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "Projektový management si vedieme individuálne podľa štandardov metodológie projektového manažmentu IPMA.",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 0,
		"pmQuality": 3
	},
	{
		"timestamp": "3/25/2015 10:03:47",
		"businessArea": "Administrative services",
		"international": "Yes",
		"startup": "No",
		"employees": 15,
		"tool": "Basecamp",
		"anotherTool": "",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "No",
		"timeScheduling": "Yes",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 4,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "3/26/2015 11:16:31",
		"businessArea": "Media publisher",
		"international": "Yes",
		"startup": "Yes",
		"employees": 30,
		"tool": "Trello",
		"anotherTool": "Github, Google docs, Hackpad",
		"license": "Licensed",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "No",
		"document": "Yes",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "No",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "",
		"blank": null,
		"importanceOfSm": 2,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 3
	},
	{
		"timestamp": "3/27/2015 9:45:38",
		"businessArea": "Machine learning",
		"international": "Yes",
		"startup": "Yes",
		"employees": 15,
		"tool": "Basecamp",
		"anotherTool": "",
		"license": "Free",
		"webBased": "Yes",
		"toolType": "Used as a service",
		"collaborative": "Yes",
		"issueTracking": "Yes",
		"timeScheduling": "No",
		"portfolio": null,
		"workflow": "No",
		"document": "No",
		"reportingAnalysis": "No",
		"timeTracking": null,
		"invoicing": "No",
		"processes": "No",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "No",
		"iso": "None",
		"softwareManagementTools": "Yes",
		"smHow": "basecamp.com",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 3,
		"pmQuality": 4
	},
	{
		"timestamp": "08/04/15 07:22 PM",
		"businessArea": "Administrative services",
		"international": "No",
		"startup": "Yes",
		"employees": 7,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "",
		"toolType": "",
		"collaborative": "",
		"issueTracking": "",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "",
		"document": "",
		"reportingAnalysis": "",
		"timeTracking": null,
		"invoicing": "",
		"processes": "No",
		"projectManager": "No",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "None",
		"softwareManagementTools": "No",
		"smHow": "We communicate by email but we are looking for some software project management tool",
		"blank": null,
		"importanceOfSm": 5,
		"satisfaction": 2,
		"difficulty": 0,
		"pmQuality": 3
	},
	{
		"timestamp": "08/04/15 07:29 PM",
		"businessArea": "Management/marketing",
		"international": "No",
		"startup": "Yes",
		"employees": 15,
		"tool": "None",
		"anotherTool": "",
		"license": "None",
		"webBased": "",
		"toolType": "",
		"collaborative": "",
		"issueTracking": "",
		"timeScheduling": "",
		"portfolio": null,
		"workflow": "",
		"document": "",
		"reportingAnalysis": "",
		"timeTracking": null,
		"invoicing": "",
		"processes": "Yes",
		"projectManager": "Yes",
		"internalMethodology": null,
		"resultsAnalysis": "Don't know",
		"iso": "ISO 10006",
		"softwareManagementTools": "No",
		"smHow": "we use email and mobile",
		"blank": null,
		"importanceOfSm": 3,
		"satisfaction": 3,
		"difficulty": 0,
		"pmQuality": 3
	}];